wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: huggingface
    huggingface_version: 4.11.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1635385590
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      3:
      - 2
      - 3
      - 8
      - 13
      - 16
      4: 3.7.12
      5: 0.12.6
      6: 4.11.3
      8:
      - 1
      - 5
architecture:
  desc: null
  value: LSTM
batch_size:
  desc: null
  value: 32
dataset:
  desc: null
  value: data-vietnames-sentiment-analyst
epochs:
  desc: null
  value: 50
learning_rate:
  desc: null
  value: 0.005
loss_function:
  desc: null
  value: categorical_crossentropy
